version: '3.3'
services:
  laden:
    image: laden:1.0
    container_name: laden
    ports:
    - 6543/udp
    - 6432/tcp
  sensor:
    image: sensor:1.0
    depends_on:
      - laden
    deploy:
      replicas: 5