#System with rabbitmq
version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15691:15691
      - 15692:15692
      - 25672:25672
      - 15671:15671
      - 15672:15672
      - 5672:5672
    networks:
      - rabbitmq_network
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 20s
      retries: 5
  monitor:
    image: monitor:1.0
    container_name: monitor
    restart: on-failure
    networks:
      - rabbitmq_network
    depends_on:
      rabbitmq:
        condition: service_healthy
  laden-1:
    image: laden:1.0
    container_name: laden-1
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
    - 6543/udp
    - 6432/tcp
    networks:
      - rabbitmq_network
  laden-2:
    image: laden:1.0
    container_name: laden-2
    restart: on-failure
    command: laden-1
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 6543/udp
      - 6432/tcp
    networks:
      - rabbitmq_network
  laden-3:
    image: laden:1.0
    container_name: laden-3
    restart: on-failure
    command: laden-2
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 6543/udp
      - 6432/tcp
    networks:
      - rabbitmq_network
  laden-4:
    image: laden:1.0
    container_name: laden-4
    restart: on-failure
    command: laden-3
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 6543/udp
      - 6432/tcp
    networks:
      - rabbitmq_network
  laden-5:
    image: laden:1.0
    container_name: laden-5
    restart: on-failure
    command: laden-4
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - 6543/udp
      - 6432/tcp
    networks:
      - rabbitmq_network
  sensor-laden-1:
    image: sensor:1.0
    command: laden-1
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 10
    networks:
      - rabbitmq_network
  sensor-laden-2:
    image: sensor:1.0
    command: laden-2
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 10
    networks:
      - rabbitmq_network
  sensor-laden-3:
    image: sensor:1.0
    command: laden-3
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 10
    networks:
      - rabbitmq_network
  sensor-laden-4:
    image: sensor:1.0
    command: laden-4
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 10
    networks:
      - rabbitmq_network
  sensor-laden-5:
    image: sensor:1.0
    command: laden-5
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    deploy:
      replicas: 10
    networks:
      - rabbitmq_network
networks:
  rabbitmq_network:
    driver: bridge



#system without rabbitmq
#version: '3.3'
#services:
#  monitor:
#    image: monitor:1.0
#    container_name: monitor
#  laden-1:
#    image: laden:1.0
#    container_name: laden-1
#    ports:
#      - 6543/udp
#      - 6432/tcp
#  laden-2:
#    image: laden:1.0
#    container_name: laden-2
#    command: laden-1
#    depends_on:
#      - laden-1
#    ports:
#      - 6543/udp
#      - 6432/tcp
#  laden-3:
#    image: laden:1.0
#    container_name: laden-3
#    command: laden-2
#    depends_on:
#      - laden-2
#    ports:
#      - 6543/udp
#      - 6432/tcp
#  sensor-laden-1:
#    image: sensor:1.0
#    command: laden-1
#    depends_on:
#      - laden-1
#    deploy:
#      replicas: 3
#  sensor-laden-2:
#    image: sensor:1.0
#    command: laden-2
#    depends_on:
#      - laden-2
#    deploy:
#      replicas: 3

#use for rabbitmq stress testing
#version: '3.3'
#services:
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    hostname: rabbitmq
#    ports:
#      - 15691:15691
#      - 15692:15692
#      - 25672:25672
#      - 15671:15671
#      - 15672:15672
#      - 5672:5672
#    networks:
#      - rabbitmq_network
#    healthcheck:
#      test: [ "CMD", "rabbitmqctl", "status" ]
#      interval: 5s
#      timeout: 20s
#      retries: 5
#  monitor:
#    image: monitor:1.0
#    container_name: monitor
#    restart: on-failure
#    networks:
#      - rabbitmq_network
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#  laden-1:
#    image: laden:1.0
#    container_name: laden-1
#    restart: on-failure
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    ports:
#      - 6543/udp
#      - 6432/tcp
#    networks:
#      - rabbitmq_network
#networks:
#  rabbitmq_network:
#    driver: bridge


#used for udp stress testing
#version: '3.3'
#services:
#  laden-1:
#    image: laden:1.0
#    container_name: laden-1
#    ports:
#      - 6543/udp
#      - 6432/tcp
#  sensor-laden-1:
#    image: sensor:1.0
#    command: laden-1
#    depends_on:
#      - laden-1
#    deploy:
#      replicas: 70


#used for rpc stress testing
#version: '3.3'
#services:
#  laden-1:
#    image: laden:1.0
#    container_name: laden-1
#    ports:
#    - 6543/udp
#    - 6432/tcp
#  laden-2:
#    image: laden:1.0
#    container_name: laden-2
#    command: laden-1
#    depends_on:
#      - laden-1
#    ports:
#      - 6543/udp
#      - 6432/tcp

#use for tcp stress testing
#version: '3.3'
#services:
#  laden-1:
#    image: laden:1.0
#    container_name: laden-1
#    ports:
#      - 6543/udp
#      - 6432/tcp